#!/usr/bin/env node
/**
 * Vendors the two typefaces the app shares with blozanod.me into public/fonts/.
 *
 * PolyRead is a subpage of that site and has to look like one, which means
 * Archivo and IBM Plex Mono. It is also a local-first app whose whole claim is
 * that nothing leaves the machine, so it cannot fetch them from Google at
 * runtime — an offline copy would fall back to system fonts, and an online one
 * would announce every reader to a third party.
 *
 * So the files are downloaded once, here, into the repository. Only the latin
 * and latin-ext subsets: this reads English-language academic PDFs, and the
 * Vietnamese, Greek and Cyrillic cuts are bytes nobody will render.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "..", "public", "fonts");

// Google serves a different @font-face block per browser; this UA is what gets
// the woff2, variable-axis version rather than the legacy static fallbacks.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const FAMILIES = [
  // Archivo carries a weight axis, so 400-900 is one file rather than six.
  { css: "Archivo:ital,wght@0,400..900", name: "archivo" },
  { css: "IBM+Plex+Mono:wght@400;500;600;700", name: "plex-mono" },
];

/** The subsets worth shipping. Everything else is dropped on the floor. */
const SUBSETS = new Set(["latin", "latin-ext"]);

async function get(url, asText) {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) throw new Error(`${response.status} from ${url}`);
  return asText ? response.text() : Buffer.from(await response.arrayBuffer());
}

async function main() {
  await mkdir(outDir, { recursive: true });
  const blocks = [];

  for (const family of FAMILIES) {
    const css = await get(
      `https://fonts.googleapis.com/css2?family=${family.css}&display=swap`,
      true,
    );

    // Google emits `/* subset */` immediately before each @font-face.
    const faces = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
    let index = 0;
    for (const [, subset, face] of faces) {
      if (!SUBSETS.has(subset)) continue;
      const url = /url\((https:\/\/[^)]+)\)/.exec(face)?.[1];
      if (!url) continue;

      const file = `${family.name}-${subset}-${index++}.woff2`;
      await writeFile(join(outDir, file), await get(url, false));
      blocks.push(face.replace(url, `./${file}`).replace(/\n\s*/g, "\n  ").trim());
      console.log(`  ${file}`);
    }
  }

  const header = [
    "/* Generated by scripts/fetch-fonts.mjs — do not edit.",
    "   Archivo and IBM Plex Mono, latin and latin-ext only, served from this",
    "   app's own origin so it works offline and phones nobody. */",
    "",
  ].join("\n");
  await writeFile(join(outDir, "fonts.css"), `${header}${blocks.join("\n\n")}\n`);
  console.log(`\n${blocks.length} faces -> public/fonts/fonts.css`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
